<?php
/**
 * The template for displaying the footer.
 *
 * Contains the closing of the id=main div and all content
 * after.  Calls sidebar-footer.php for bottom widgets.
 *
 * @package WordPress
 * @subpackage Boilerplate
 * @since Boilerplate 1.0
 */
?>
		<div id="footer-wraper">
		<footer class="container container-twelve">
			<div class="three columns">
				<div class="widget-container">
					<h3><span>About orcur</span></h3>
						<p>Orcur is a theme design for event planning and management.</p>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi imperdiet tortor id</p>
				</div><!-- .widget-container -->
			</div><!-- .three -->
			<div class="three columns">
				<div class="widget-container">
					<h3><span>Latest News</span></h3>
					<p>
						<a href="#">Sao Paublo recalls at the end of August</a>
						<br />
						<span class="small">by <a href="#">Joe Dows</a> on <strong>July 26</strong></span>
					</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi imperdiet tortor id ligula vulputate. <a href="#">( Read More &rarr; )</a></p>
				</div><!-- .widget-container -->
			</div><!-- .three -->
			<div class="three columns">
				<div class="widget-container">
					<h3><span>When and Where?</span></h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi imperdiet</p>
					<p>Premium Club - 10:00a<br />
					Elites Membership - 10:30a<br />
					AM Package - 11:30</p>
				</div><!-- .widget-container -->
			</div><!-- .three -->
			<div class="three columns">
				<div class="widget-container">
					<h3><span>Newsletter</span></h3>
					<p>Fusce cursus aliquam aliquet. Sed pretium auctor nunc elandit estibulum</p>
					<div class="newsletter-box">
						<input type="text" name="email" id="email" placeholder="Your Email" />
						<input type="button" name="submit" id="submit" value="Submit" />
					</div>
				</div><!-- .widget-container -->
			</div><!-- .three -->
		</footer><!-- .container -->
		<div id="footer-bottom-wraper">
			<div id="footer-bottom" class="container container-twelve">
				<div id="footer-info" class="six columns">
					<span>&copy; 2012 <a href="#">Orcur</a>. Powered by <a href="#">HTML5/CSS3</a><br />
					<a href="#">Orcur Theme</a> by <a href="#">Rene Merino</a></span>
				</div><!-- #footer-info -->
				<div id="social" class="six columns">
		    		<ul>
		    			<li>Find Us on:</li>
		    			<li class="twitter"><a href="#">Twitter</a></li>
		    			<li class="facebook"><a href="#">Facebook</a></li>
		    			<li class="vimeo"><a href="#">Vimeo</a></li>
		    			<li class="youtube"><a href="#">Youtube</a></li>
		    			<li class="skype"><a href="#">Skype</a></li>
		    		</ul>
		    	</div><!-- end #social -->
			</div><!-- .container -->
		</div><!-- #footer-bottom-wraper -->
	</div><!-- #footer-wraper -->
		
		
		
	<!-- JavaScript
	================================================== -->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	
	<!-- All Scripts -->
	<script type="text/javascript" src="<?php echo get_bloginfo( 'wpurl' ) ?>/wp-content/themes/bsdc/js/scripts.js"></script>
	<!-- jQuery Countdown -->
	<script type="text/javascript" src="<?php echo get_bloginfo( 'wpurl' ) ?>/wp-content/themes/bsdc/js/jquery.countdown.min.js"></script>
	<!-- Easing plugin -->
	<script type="text/javascript" src="<?php echo get_bloginfo( 'wpurl' ) ?>/wp-content/themes/bsdc/js/jquery.easing.1.3.js"></script>
	<!-- FlexSlider -->
	<script type="text/javascript" src="<?php echo get_bloginfo( 'wpurl' ) ?>/wp-content/themes/bsdc/js/jquery.flexslider-min.js"></script>
	<!-- prettyPhoto -->
	<script src="<?php echo get_bloginfo( 'wpurl' ) ?>/wp-content/themes/bsdc/js/prettyPhoto/js/jquery.prettyPhoto.js"></script>
	<link rel="stylesheet" href="js/prettyPhoto/css/prettyPhoto.css" media="screen" />
	
	<script>
	
	$(window).load(function() {
	
		/* Carousel */
		$('#carousel').flexslider({
			animation: "slide",
			animationLoop: true,
			itemWidth: 150,
			itemMargin: 50,
			controlNav: false,
			slideshowSpeed: 5000,          
			animationSpeed: 600
		});
	
		$('.flexslider').flexslider({
			namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
			selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
			animation: "slide",              //String: Select your animation type, "fade" or "slide"
			easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
			direction: "horizontal",        //String: Select the sliding direction, "horizontal" or "vertical"
			reverse: false,                 //{NEW} Boolean: Reverse the animation direction
			animationLoop: true,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
			smoothHeight: false,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode
			startAt: 0,                     //Integer: The slide that the slider should start on. Array notation (0 = first slide)
			slideshow: true,                //Boolean: Animate slider automatically
			slideshowSpeed: 7000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
			animationSpeed: 600,            //Integer: Set the speed of animations, in milliseconds
			initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
			randomize: false,               //Boolean: Randomize slide order
			 
			// Usability features
			pauseOnAction: true,            //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
			pauseOnHover: false,            //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
			useCSS: true,                   //{NEW} Boolean: Slider will use CSS3 transitions if available
			touch: true,                    //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
			video: false,                   //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
			 
			// Primary Controls
			controlNav: true,               //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
			directionNav: true,             //Boolean: Create navigation for previous/next navigation? (true/false)
			prevText: "Previous",           //String: Set the text for the "previous" directionNav item
			nextText: "Next",               //String: Set the text for the "next" directionNav item
			 
			// Secondary Navigation
			keyboard: true,                 //Boolean: Allow slider navigating via keyboard left/right keys
			multipleKeyboard: false,        //{NEW} Boolean: Allow keyboard navigation to affect multiple sliders. Default behavior cuts out keyboard navigation with more than one slider present.
			mousewheel: false,              //{UPDATED} Boolean: Requires jquery.mousewheel.js (https://github.com/brandonaaron/jquery-mousewheel) - Allows slider navigating via mousewheel
			pausePlay: false,               //Boolean: Create pause/play dynamic element
			pauseText: 'Pause',             //String: Set the text for the "pause" pausePlay item
			playText: 'Play',               //String: Set the text for the "play" pausePlay item
			 
			// Special properties
			controlsContainer: "",          //{UPDATED} Selector: USE CLASS SELECTOR. Declare which container the navigation elements should be appended too. Default container is the FlexSlider element. Example use would be ".flexslider-container". Property is ignored if given element is not found.
			manualControls: "",             //Selector: Declare custom control navigation. Examples would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
			sync: "",                       //{NEW} Selector: Mirror the actions performed on this slider with another slider. Use with care.
			asNavFor: "",                   //{NEW} Selector: Internal property exposed for turning the slider into a thumbnail navigation for another slider
			 
			// Carousel Options
			itemWidth: 0,                   //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
			itemMargin: 0,                  //{NEW} Integer: Margin between carousel items.
			minItems: 0,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
			maxItems: 0,                    //{NEW} Integer: Maxmimum number of carousel items that should be visible. Items will resize fluidly when above this limit.
			move: 0,                        //{NEW} Integer: Number of carousel items that should move on animation. If 0, slider will move all visible items.
			 
			// Callback API
			start: function(){},            //Callback: function(slider) - Fires when the slider loads the first slide
			before: function(){},           //Callback: function(slider) - Fires asynchronously with each slider animation
			after: function(){},            //Callback: function(slider) - Fires after each slider animation completes
			end: function(){},              //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
			added: function(){},            //{NEW} Callback: function(slider) - Fires after a slide is added
			removed: function(){} 
		});
	});
	</script>
	
	<!-- Twitter -->
	<script src="http://twitterjs.googlecode.com/svn/trunk/src/twitter.min.js"></script>
	<script>
	getTwitters('tweet', { 
		id: 'bigskydevcon', 
		count: 1, 
		enableLinks: true, 
		ignoreReplies: true, 
		clearContents: true,
		template: '"%text%" <a href="http://twitter.com/%user_screen_name%/statuses/%id_str%/">%time%</a>'
	});
	</script>
	
		<!-- StyleSwitcher -->
	<script src="<?php echo get_bloginfo( 'wpurl' ) ?>/wp-content/themes/bsdc/js/style-switcher/styleswitch.js"></script>
	<script src="<?php echo get_bloginfo( 'wpurl' ) ?>/wp-content/themes/bsdc/js/style-switcher/switcher.js"></script>
	<link rel="stylesheet" href="<?php echo get_bloginfo( 'wpurl' ) ?>/wp-content/themes/bsdc/js/style-switcher/switcher.css" />

	
<?php
	/* Always have wp_footer() just before the closing </body>
	 * tag of your theme, or you will break many plugins, which
	 * generally use this hook to reference JavaScript files.
	 */
	wp_footer();
?>
	</body>
</html>